# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

brew_packages:
  - gcc

use_bioc: true
bioc_required: true

bioc_packages:
  - biomformat
  - phyloseq
